name: Solve
run-name: Solve-${{ inputs.year }}-${{ inputs.day }}

on:
  workflow_dispatch:
    inputs:
      day:
        description: Day
        required: true
        default: '07'
        type: choice
        options:
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          - '07'
          - '08'
          - '09'
          - '10'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
          - '23'
          - '24'
          - '25'
      year:
        description: Year
        required: true
        default: '2023'
        type: choice
        options:
          - '2015'
          - '2016'
          - '2017'
          - '2018'
          - '2019'
          - '2020'
          - '2021'
          - '2022'
          - '2023'
          - '2024'
      language:
        description: Language to use
        required: true
        default: 'python'
        type: choice
        options:
          - 'python'
          - 'rust'
      timeout:
        description: Job timeout
        required: false
        type: number
        default: 1

permissions:
  contents: read
  
jobs:
  solve:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.timeout) }}
    defaults:
      run:
        shell: bash
        working-directory: ./${{ inputs.year }}/${{ inputs.day }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.year }}/${{ inputs.day }}/
          persist-credentials: false
          
      - name: Solve (python)
        if: ${{ inputs.language == 'python' }}
        run: python ./solve.py

      - name: Solve (rust)
        if: ${{ inputs.language == 'rust' }}
        run: cargo run --release
