name: Solve

on:
  workflow_dispatch:
    inputs:
      day:
        description: 'Day'
        required: true
        default: '05'
        type: choice
        options:
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          - '07'
          - '08'
          - '09'
          - '10'
      year:
        description: 'Year'
        required: true
        default: '2023'
        type: choice
        options:
          - '2023'
          - '2024'
jobs:
  solve:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./${{ inputs.year }}/${{ inputs.day }}
    steps:   
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.year }}/${{ inputs.day }}/

      - name: Solve
        run: python ./solve.py
