name: Solve

on:
  workflow_dispatch:

jobs:
  solve:
    runs-on: ubuntu-latest
    env:
      YEAR: '2024'
      DAY: '01'
    steps:   
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ env.YEAR}}/${{ env.DAY }}/

      - name: Solve
        run: python ./${{env.YEAR }}/${{ env.DAY }}/solve.py
    
    
